FROM nginx

RUN rm /etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf
# Remove default nginx configuration file


# # Copy custom nginx configuration file
# COPY default.conf /etc/nginx/conf.d/

# Expose port 80
EXPOSE 80

# # Start nginx
CMD ["nginx", "-g", "daemon off;"]
